#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class RecommendType:
  SALESMAN = 1

  _VALUES_TO_NAMES = {
    1: "SALESMAN",
  }

  _NAMES_TO_VALUES = {
    "SALESMAN": 1,
  }


class UserCate:
  """
  Attributes:
   - code
   - name
   - ctime
   - status
   - remark
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'code', None, None, ), # 1
    (2, TType.STRING, 'name', None, None, ), # 2
    (3, TType.STRING, 'ctime', None, None, ), # 3
    (4, TType.I32, 'status', None, 1, ), # 4
    (5, TType.STRING, 'remark', None, "", ), # 5
  )

  def __init__(self, code=None, name=None, ctime=None, status=thrift_spec[4][4], remark=thrift_spec[5][4],):
    self.code = code
    self.name = name
    self.ctime = ctime
    self.status = status
    self.remark = remark

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.code = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.name = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.ctime = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.status = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.remark = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('UserCate')
    if self.code is not None:
      oprot.writeFieldBegin('code', TType.STRING, 1)
      oprot.writeString(self.code)
      oprot.writeFieldEnd()
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 2)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.ctime is not None:
      oprot.writeFieldBegin('ctime', TType.STRING, 3)
      oprot.writeString(self.ctime)
      oprot.writeFieldEnd()
    if self.status is not None:
      oprot.writeFieldBegin('status', TType.I32, 4)
      oprot.writeI32(self.status)
      oprot.writeFieldEnd()
    if self.remark is not None:
      oprot.writeFieldBegin('remark', TType.STRING, 5)
      oprot.writeString(self.remark)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.code is None:
      raise TProtocol.TProtocolException(message='Required field code is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.code)
    value = (value * 31) ^ hash(self.name)
    value = (value * 31) ^ hash(self.ctime)
    value = (value * 31) ^ hash(self.status)
    value = (value * 31) ^ hash(self.remark)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class UserTag:
  """
  Attributes:
   - name
   - ctime
   - content
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'name', None, None, ), # 1
    (2, TType.STRING, 'ctime', None, None, ), # 2
    (3, TType.STRING, 'content', None, None, ), # 3
  )

  def __init__(self, name=None, ctime=None, content=None,):
    self.name = name
    self.ctime = ctime
    self.content = content

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.name = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.ctime = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.content = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('UserTag')
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 1)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.ctime is not None:
      oprot.writeFieldBegin('ctime', TType.STRING, 2)
      oprot.writeString(self.ctime)
      oprot.writeFieldEnd()
    if self.content is not None:
      oprot.writeFieldBegin('content', TType.STRING, 3)
      oprot.writeString(self.content)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.name is None:
      raise TProtocol.TProtocolException(message='Required field name is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.name)
    value = (value * 31) ^ hash(self.ctime)
    value = (value * 31) ^ hash(self.content)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class UserService:
  """
  Attributes:
   - code
   - name
   - starttime
   - endtime
   - status
   - memo
   - ctime
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'code', None, None, ), # 1
    (2, TType.STRING, 'name', None, None, ), # 2
    (3, TType.STRING, 'starttime', None, None, ), # 3
    (4, TType.STRING, 'endtime', None, None, ), # 4
    (5, TType.I32, 'status', None, None, ), # 5
    (6, TType.STRING, 'memo', None, None, ), # 6
    (7, TType.STRING, 'ctime', None, None, ), # 7
  )

  def __init__(self, code=None, name=None, starttime=None, endtime=None, status=None, memo=None, ctime=None,):
    self.code = code
    self.name = name
    self.starttime = starttime
    self.endtime = endtime
    self.status = status
    self.memo = memo
    self.ctime = ctime

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.code = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.name = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.starttime = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.endtime = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.status = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRING:
          self.memo = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.ctime = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('UserService')
    if self.code is not None:
      oprot.writeFieldBegin('code', TType.STRING, 1)
      oprot.writeString(self.code)
      oprot.writeFieldEnd()
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 2)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.starttime is not None:
      oprot.writeFieldBegin('starttime', TType.STRING, 3)
      oprot.writeString(self.starttime)
      oprot.writeFieldEnd()
    if self.endtime is not None:
      oprot.writeFieldBegin('endtime', TType.STRING, 4)
      oprot.writeString(self.endtime)
      oprot.writeFieldEnd()
    if self.status is not None:
      oprot.writeFieldBegin('status', TType.I32, 5)
      oprot.writeI32(self.status)
      oprot.writeFieldEnd()
    if self.memo is not None:
      oprot.writeFieldBegin('memo', TType.STRING, 6)
      oprot.writeString(self.memo)
      oprot.writeFieldEnd()
    if self.ctime is not None:
      oprot.writeFieldBegin('ctime', TType.STRING, 7)
      oprot.writeString(self.ctime)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.code is None:
      raise TProtocol.TProtocolException(message='Required field code is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.code)
    value = (value * 31) ^ hash(self.name)
    value = (value * 31) ^ hash(self.starttime)
    value = (value * 31) ^ hash(self.endtime)
    value = (value * 31) ^ hash(self.status)
    value = (value * 31) ^ hash(self.memo)
    value = (value * 31) ^ hash(self.ctime)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class BankInfo:
  """
  Attributes:
   - headbankname
   - bankuser
   - bankaccount
   - banktype
   - bankname
   - bankcode
   - bankProvince
   - bankCity
   - bankmobile
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'headbankname', None, None, ), # 1
    (2, TType.STRING, 'bankuser', None, None, ), # 2
    (3, TType.STRING, 'bankaccount', None, None, ), # 3
    (4, TType.I32, 'banktype', None, 1, ), # 4
    (5, TType.STRING, 'bankname', None, None, ), # 5
    (6, TType.STRING, 'bankcode', None, None, ), # 6
    (7, TType.STRING, 'bankProvince', None, "", ), # 7
    (8, TType.STRING, 'bankCity', None, "", ), # 8
    (9, TType.STRING, 'bankmobile', None, "", ), # 9
  )

  def __init__(self, headbankname=None, bankuser=None, bankaccount=None, banktype=thrift_spec[4][4], bankname=None, bankcode=None, bankProvince=thrift_spec[7][4], bankCity=thrift_spec[8][4], bankmobile=thrift_spec[9][4],):
    self.headbankname = headbankname
    self.bankuser = bankuser
    self.bankaccount = bankaccount
    self.banktype = banktype
    self.bankname = bankname
    self.bankcode = bankcode
    self.bankProvince = bankProvince
    self.bankCity = bankCity
    self.bankmobile = bankmobile

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.headbankname = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.bankuser = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.bankaccount = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.banktype = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.bankname = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRING:
          self.bankcode = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.bankProvince = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.bankCity = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.STRING:
          self.bankmobile = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('BankInfo')
    if self.headbankname is not None:
      oprot.writeFieldBegin('headbankname', TType.STRING, 1)
      oprot.writeString(self.headbankname)
      oprot.writeFieldEnd()
    if self.bankuser is not None:
      oprot.writeFieldBegin('bankuser', TType.STRING, 2)
      oprot.writeString(self.bankuser)
      oprot.writeFieldEnd()
    if self.bankaccount is not None:
      oprot.writeFieldBegin('bankaccount', TType.STRING, 3)
      oprot.writeString(self.bankaccount)
      oprot.writeFieldEnd()
    if self.banktype is not None:
      oprot.writeFieldBegin('banktype', TType.I32, 4)
      oprot.writeI32(self.banktype)
      oprot.writeFieldEnd()
    if self.bankname is not None:
      oprot.writeFieldBegin('bankname', TType.STRING, 5)
      oprot.writeString(self.bankname)
      oprot.writeFieldEnd()
    if self.bankcode is not None:
      oprot.writeFieldBegin('bankcode', TType.STRING, 6)
      oprot.writeString(self.bankcode)
      oprot.writeFieldEnd()
    if self.bankProvince is not None:
      oprot.writeFieldBegin('bankProvince', TType.STRING, 7)
      oprot.writeString(self.bankProvince)
      oprot.writeFieldEnd()
    if self.bankCity is not None:
      oprot.writeFieldBegin('bankCity', TType.STRING, 8)
      oprot.writeString(self.bankCity)
      oprot.writeFieldEnd()
    if self.bankmobile is not None:
      oprot.writeFieldBegin('bankmobile', TType.STRING, 9)
      oprot.writeString(self.bankmobile)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.headbankname is None:
      raise TProtocol.TProtocolException(message='Required field headbankname is unset!')
    if self.bankuser is None:
      raise TProtocol.TProtocolException(message='Required field bankuser is unset!')
    if self.bankaccount is None:
      raise TProtocol.TProtocolException(message='Required field bankaccount is unset!')
    if self.banktype is None:
      raise TProtocol.TProtocolException(message='Required field banktype is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.headbankname)
    value = (value * 31) ^ hash(self.bankuser)
    value = (value * 31) ^ hash(self.bankaccount)
    value = (value * 31) ^ hash(self.banktype)
    value = (value * 31) ^ hash(self.bankname)
    value = (value * 31) ^ hash(self.bankcode)
    value = (value * 31) ^ hash(self.bankProvince)
    value = (value * 31) ^ hash(self.bankCity)
    value = (value * 31) ^ hash(self.bankmobile)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class User:
  """
  Attributes:
   - uid
   - name
   - shopname
   - email
   - mobile
   - telephone
   - password
   - state
   - idnumber
   - province
   - city
   - mcc
   - address
   - longitude
   - latitude
   - userCates
   - jointime
   - risklevel
   - groupid
   - user_type
   - legalperson
   - businessaddr
   - licensenumber
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'uid', None, 0, ), # 1
    (2, TType.STRING, 'name', None, "", ), # 2
    (3, TType.STRING, 'shopname', None, "", ), # 3
    (4, TType.STRING, 'email', None, "", ), # 4
    (5, TType.STRING, 'mobile', None, "", ), # 5
    (6, TType.STRING, 'telephone', None, None, ), # 6
    (7, TType.STRING, 'password', None, None, ), # 7
    (8, TType.I32, 'state', None, None, ), # 8
    (9, TType.STRING, 'idnumber', None, None, ), # 9
    (10, TType.STRING, 'province', None, None, ), # 10
    (11, TType.STRING, 'city', None, None, ), # 11
    (12, TType.STRING, 'mcc', None, None, ), # 12
    (13, TType.STRING, 'address', None, None, ), # 13
    (14, TType.DOUBLE, 'longitude', None, 0, ), # 14
    (15, TType.DOUBLE, 'latitude', None, 0, ), # 15
    (16, TType.LIST, 'userCates', (TType.STRUCT,(UserCate, UserCate.thrift_spec)), None, ), # 16
    (17, TType.STRING, 'jointime', None, None, ), # 17
    (18, TType.I32, 'risklevel', None, 0, ), # 18
    (19, TType.I32, 'groupid', None, 0, ), # 19
    (20, TType.I32, 'user_type', None, 1, ), # 20
    (21, TType.STRING, 'legalperson', None, None, ), # 21
    (22, TType.STRING, 'businessaddr', None, None, ), # 22
    (23, TType.STRING, 'licensenumber', None, None, ), # 23
  )

  def __init__(self, uid=thrift_spec[1][4], name=thrift_spec[2][4], shopname=thrift_spec[3][4], email=thrift_spec[4][4], mobile=thrift_spec[5][4], telephone=None, password=None, state=None, idnumber=None, province=None, city=None, mcc=None, address=None, longitude=thrift_spec[14][4], latitude=thrift_spec[15][4], userCates=None, jointime=None, risklevel=thrift_spec[18][4], groupid=thrift_spec[19][4], user_type=thrift_spec[20][4], legalperson=None, businessaddr=None, licensenumber=None,):
    self.uid = uid
    self.name = name
    self.shopname = shopname
    self.email = email
    self.mobile = mobile
    self.telephone = telephone
    self.password = password
    self.state = state
    self.idnumber = idnumber
    self.province = province
    self.city = city
    self.mcc = mcc
    self.address = address
    self.longitude = longitude
    self.latitude = latitude
    self.userCates = userCates
    self.jointime = jointime
    self.risklevel = risklevel
    self.groupid = groupid
    self.user_type = user_type
    self.legalperson = legalperson
    self.businessaddr = businessaddr
    self.licensenumber = licensenumber

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.uid = iprot.readI64()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.name = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.shopname = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.email = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.mobile = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRING:
          self.telephone = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.password = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.I32:
          self.state = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.STRING:
          self.idnumber = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.STRING:
          self.province = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.STRING:
          self.city = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 12:
        if ftype == TType.STRING:
          self.mcc = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 13:
        if ftype == TType.STRING:
          self.address = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 14:
        if ftype == TType.DOUBLE:
          self.longitude = iprot.readDouble()
        else:
          iprot.skip(ftype)
      elif fid == 15:
        if ftype == TType.DOUBLE:
          self.latitude = iprot.readDouble()
        else:
          iprot.skip(ftype)
      elif fid == 16:
        if ftype == TType.LIST:
          self.userCates = []
          (_etype3, _size0) = iprot.readListBegin()
          for _i4 in xrange(_size0):
            _elem5 = UserCate()
            _elem5.read(iprot)
            self.userCates.append(_elem5)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 17:
        if ftype == TType.STRING:
          self.jointime = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 18:
        if ftype == TType.I32:
          self.risklevel = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 19:
        if ftype == TType.I32:
          self.groupid = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.I32:
          self.user_type = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 21:
        if ftype == TType.STRING:
          self.legalperson = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 22:
        if ftype == TType.STRING:
          self.businessaddr = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 23:
        if ftype == TType.STRING:
          self.licensenumber = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('User')
    if self.uid is not None:
      oprot.writeFieldBegin('uid', TType.I64, 1)
      oprot.writeI64(self.uid)
      oprot.writeFieldEnd()
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 2)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.shopname is not None:
      oprot.writeFieldBegin('shopname', TType.STRING, 3)
      oprot.writeString(self.shopname)
      oprot.writeFieldEnd()
    if self.email is not None:
      oprot.writeFieldBegin('email', TType.STRING, 4)
      oprot.writeString(self.email)
      oprot.writeFieldEnd()
    if self.mobile is not None:
      oprot.writeFieldBegin('mobile', TType.STRING, 5)
      oprot.writeString(self.mobile)
      oprot.writeFieldEnd()
    if self.telephone is not None:
      oprot.writeFieldBegin('telephone', TType.STRING, 6)
      oprot.writeString(self.telephone)
      oprot.writeFieldEnd()
    if self.password is not None:
      oprot.writeFieldBegin('password', TType.STRING, 7)
      oprot.writeString(self.password)
      oprot.writeFieldEnd()
    if self.state is not None:
      oprot.writeFieldBegin('state', TType.I32, 8)
      oprot.writeI32(self.state)
      oprot.writeFieldEnd()
    if self.idnumber is not None:
      oprot.writeFieldBegin('idnumber', TType.STRING, 9)
      oprot.writeString(self.idnumber)
      oprot.writeFieldEnd()
    if self.province is not None:
      oprot.writeFieldBegin('province', TType.STRING, 10)
      oprot.writeString(self.province)
      oprot.writeFieldEnd()
    if self.city is not None:
      oprot.writeFieldBegin('city', TType.STRING, 11)
      oprot.writeString(self.city)
      oprot.writeFieldEnd()
    if self.mcc is not None:
      oprot.writeFieldBegin('mcc', TType.STRING, 12)
      oprot.writeString(self.mcc)
      oprot.writeFieldEnd()
    if self.address is not None:
      oprot.writeFieldBegin('address', TType.STRING, 13)
      oprot.writeString(self.address)
      oprot.writeFieldEnd()
    if self.longitude is not None:
      oprot.writeFieldBegin('longitude', TType.DOUBLE, 14)
      oprot.writeDouble(self.longitude)
      oprot.writeFieldEnd()
    if self.latitude is not None:
      oprot.writeFieldBegin('latitude', TType.DOUBLE, 15)
      oprot.writeDouble(self.latitude)
      oprot.writeFieldEnd()
    if self.userCates is not None:
      oprot.writeFieldBegin('userCates', TType.LIST, 16)
      oprot.writeListBegin(TType.STRUCT, len(self.userCates))
      for iter6 in self.userCates:
        iter6.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.jointime is not None:
      oprot.writeFieldBegin('jointime', TType.STRING, 17)
      oprot.writeString(self.jointime)
      oprot.writeFieldEnd()
    if self.risklevel is not None:
      oprot.writeFieldBegin('risklevel', TType.I32, 18)
      oprot.writeI32(self.risklevel)
      oprot.writeFieldEnd()
    if self.groupid is not None:
      oprot.writeFieldBegin('groupid', TType.I32, 19)
      oprot.writeI32(self.groupid)
      oprot.writeFieldEnd()
    if self.user_type is not None:
      oprot.writeFieldBegin('user_type', TType.I32, 20)
      oprot.writeI32(self.user_type)
      oprot.writeFieldEnd()
    if self.legalperson is not None:
      oprot.writeFieldBegin('legalperson', TType.STRING, 21)
      oprot.writeString(self.legalperson)
      oprot.writeFieldEnd()
    if self.businessaddr is not None:
      oprot.writeFieldBegin('businessaddr', TType.STRING, 22)
      oprot.writeString(self.businessaddr)
      oprot.writeFieldEnd()
    if self.licensenumber is not None:
      oprot.writeFieldBegin('licensenumber', TType.STRING, 23)
      oprot.writeString(self.licensenumber)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.uid is None:
      raise TProtocol.TProtocolException(message='Required field uid is unset!')
    if self.name is None:
      raise TProtocol.TProtocolException(message='Required field name is unset!')
    if self.shopname is None:
      raise TProtocol.TProtocolException(message='Required field shopname is unset!')
    if self.email is None:
      raise TProtocol.TProtocolException(message='Required field email is unset!')
    if self.mobile is None:
      raise TProtocol.TProtocolException(message='Required field mobile is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.uid)
    value = (value * 31) ^ hash(self.name)
    value = (value * 31) ^ hash(self.shopname)
    value = (value * 31) ^ hash(self.email)
    value = (value * 31) ^ hash(self.mobile)
    value = (value * 31) ^ hash(self.telephone)
    value = (value * 31) ^ hash(self.password)
    value = (value * 31) ^ hash(self.state)
    value = (value * 31) ^ hash(self.idnumber)
    value = (value * 31) ^ hash(self.province)
    value = (value * 31) ^ hash(self.city)
    value = (value * 31) ^ hash(self.mcc)
    value = (value * 31) ^ hash(self.address)
    value = (value * 31) ^ hash(self.longitude)
    value = (value * 31) ^ hash(self.latitude)
    value = (value * 31) ^ hash(self.userCates)
    value = (value * 31) ^ hash(self.jointime)
    value = (value * 31) ^ hash(self.risklevel)
    value = (value * 31) ^ hash(self.groupid)
    value = (value * 31) ^ hash(self.user_type)
    value = (value * 31) ^ hash(self.legalperson)
    value = (value * 31) ^ hash(self.businessaddr)
    value = (value * 31) ^ hash(self.licensenumber)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class ImgInfo:
  """
  Attributes:
   - name
   - imgname
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'name', None, None, ), # 1
    (2, TType.STRING, 'imgname', None, None, ), # 2
  )

  def __init__(self, name=None, imgname=None,):
    self.name = name
    self.imgname = imgname

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.name = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.imgname = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('ImgInfo')
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 1)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.imgname is not None:
      oprot.writeFieldBegin('imgname', TType.STRING, 2)
      oprot.writeString(self.imgname)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.name is None:
      raise TProtocol.TProtocolException(message='Required field name is unset!')
    if self.imgname is None:
      raise TProtocol.TProtocolException(message='Required field imgname is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.name)
    value = (value * 31) ^ hash(self.imgname)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class RegisterAllInfo:
  """
  Attributes:
   - username
   - password
   - bankuser
   - idnumber
   - banktype
   - bankprovince
   - bankcity
   - bankname
   - headbankname
   - bankcode
   - bankaccount
   - bankmobile
   - shopname
   - province
   - city
   - address
   - landline
   - longitude
   - latitude
   - tenpay_ratio
   - alipay_ratio
   - jdpay_ratio
   - qqpay_ratio
   - credit_ratio
   - debit_ratio
   - idstatdate
   - idenddate
   - usertype
   - legalperson
   - name
   - mode
   - big_uid
   - imgInfos
   - mcc
   - groupid
   - userid
   - src
   - licensenumber
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'username', None, "", ), # 1
    (2, TType.STRING, 'password', None, "", ), # 2
    (3, TType.STRING, 'bankuser', None, "", ), # 3
    (4, TType.STRING, 'idnumber', None, "", ), # 4
    (5, TType.I32, 'banktype', None, 1, ), # 5
    (6, TType.STRING, 'bankprovince', None, "", ), # 6
    (7, TType.STRING, 'bankcity', None, "", ), # 7
    (8, TType.STRING, 'bankname', None, "", ), # 8
    (9, TType.STRING, 'headbankname', None, "", ), # 9
    (10, TType.STRING, 'bankcode', None, "", ), # 10
    (11, TType.STRING, 'bankaccount', None, "", ), # 11
    (12, TType.STRING, 'bankmobile', None, "", ), # 12
    (13, TType.STRING, 'shopname', None, None, ), # 13
    (14, TType.STRING, 'province', None, None, ), # 14
    (15, TType.STRING, 'city', None, None, ), # 15
    (16, TType.STRING, 'address', None, None, ), # 16
    (17, TType.STRING, 'landline', None, "", ), # 17
    (18, TType.DOUBLE, 'longitude', None, None, ), # 18
    (19, TType.DOUBLE, 'latitude', None, None, ), # 19
    (20, TType.STRING, 'tenpay_ratio', None, None, ), # 20
    (21, TType.STRING, 'alipay_ratio', None, None, ), # 21
    (22, TType.STRING, 'jdpay_ratio', None, None, ), # 22
    (23, TType.STRING, 'qqpay_ratio', None, None, ), # 23
    (24, TType.STRING, 'credit_ratio', None, None, ), # 24
    (25, TType.STRING, 'debit_ratio', None, None, ), # 25
    (26, TType.STRING, 'idstatdate', None, None, ), # 26
    (27, TType.STRING, 'idenddate', None, None, ), # 27
    (28, TType.I32, 'usertype', None, None, ), # 28
    (29, TType.STRING, 'legalperson', None, None, ), # 29
    (30, TType.STRING, 'name', None, None, ), # 30
    (31, TType.STRING, 'mode', None, None, ), # 31
    (32, TType.I32, 'big_uid', None, None, ), # 32
    (33, TType.LIST, 'imgInfos', (TType.STRUCT,(ImgInfo, ImgInfo.thrift_spec)), None, ), # 33
    (34, TType.STRING, 'mcc', None, None, ), # 34
    (35, TType.I32, 'groupid', None, None, ), # 35
    (36, TType.I32, 'userid', None, None, ), # 36
    (37, TType.STRING, 'src', None, None, ), # 37
    (38, TType.STRING, 'licensenumber', None, None, ), # 38
  )

  def __init__(self, username=thrift_spec[1][4], password=thrift_spec[2][4], bankuser=thrift_spec[3][4], idnumber=thrift_spec[4][4], banktype=thrift_spec[5][4], bankprovince=thrift_spec[6][4], bankcity=thrift_spec[7][4], bankname=thrift_spec[8][4], headbankname=thrift_spec[9][4], bankcode=thrift_spec[10][4], bankaccount=thrift_spec[11][4], bankmobile=thrift_spec[12][4], shopname=None, province=None, city=None, address=None, landline=thrift_spec[17][4], longitude=None, latitude=None, tenpay_ratio=None, alipay_ratio=None, jdpay_ratio=None, qqpay_ratio=None, credit_ratio=None, debit_ratio=None, idstatdate=None, idenddate=None, usertype=None, legalperson=None, name=None, mode=None, big_uid=None, imgInfos=None, mcc=None, groupid=None, userid=None, src=None, licensenumber=None,):
    self.username = username
    self.password = password
    self.bankuser = bankuser
    self.idnumber = idnumber
    self.banktype = banktype
    self.bankprovince = bankprovince
    self.bankcity = bankcity
    self.bankname = bankname
    self.headbankname = headbankname
    self.bankcode = bankcode
    self.bankaccount = bankaccount
    self.bankmobile = bankmobile
    self.shopname = shopname
    self.province = province
    self.city = city
    self.address = address
    self.landline = landline
    self.longitude = longitude
    self.latitude = latitude
    self.tenpay_ratio = tenpay_ratio
    self.alipay_ratio = alipay_ratio
    self.jdpay_ratio = jdpay_ratio
    self.qqpay_ratio = qqpay_ratio
    self.credit_ratio = credit_ratio
    self.debit_ratio = debit_ratio
    self.idstatdate = idstatdate
    self.idenddate = idenddate
    self.usertype = usertype
    self.legalperson = legalperson
    self.name = name
    self.mode = mode
    self.big_uid = big_uid
    self.imgInfos = imgInfos
    self.mcc = mcc
    self.groupid = groupid
    self.userid = userid
    self.src = src
    self.licensenumber = licensenumber

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.username = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.password = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.bankuser = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.idnumber = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.banktype = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRING:
          self.bankprovince = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.bankcity = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.bankname = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.STRING:
          self.headbankname = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.STRING:
          self.bankcode = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.STRING:
          self.bankaccount = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 12:
        if ftype == TType.STRING:
          self.bankmobile = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 13:
        if ftype == TType.STRING:
          self.shopname = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 14:
        if ftype == TType.STRING:
          self.province = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 15:
        if ftype == TType.STRING:
          self.city = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 16:
        if ftype == TType.STRING:
          self.address = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 17:
        if ftype == TType.STRING:
          self.landline = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 18:
        if ftype == TType.DOUBLE:
          self.longitude = iprot.readDouble()
        else:
          iprot.skip(ftype)
      elif fid == 19:
        if ftype == TType.DOUBLE:
          self.latitude = iprot.readDouble()
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.STRING:
          self.tenpay_ratio = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 21:
        if ftype == TType.STRING:
          self.alipay_ratio = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 22:
        if ftype == TType.STRING:
          self.jdpay_ratio = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 23:
        if ftype == TType.STRING:
          self.qqpay_ratio = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 24:
        if ftype == TType.STRING:
          self.credit_ratio = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 25:
        if ftype == TType.STRING:
          self.debit_ratio = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 26:
        if ftype == TType.STRING:
          self.idstatdate = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 27:
        if ftype == TType.STRING:
          self.idenddate = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 28:
        if ftype == TType.I32:
          self.usertype = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 29:
        if ftype == TType.STRING:
          self.legalperson = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 30:
        if ftype == TType.STRING:
          self.name = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 31:
        if ftype == TType.STRING:
          self.mode = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 32:
        if ftype == TType.I32:
          self.big_uid = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 33:
        if ftype == TType.LIST:
          self.imgInfos = []
          (_etype10, _size7) = iprot.readListBegin()
          for _i11 in xrange(_size7):
            _elem12 = ImgInfo()
            _elem12.read(iprot)
            self.imgInfos.append(_elem12)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 34:
        if ftype == TType.STRING:
          self.mcc = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 35:
        if ftype == TType.I32:
          self.groupid = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 36:
        if ftype == TType.I32:
          self.userid = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 37:
        if ftype == TType.STRING:
          self.src = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 38:
        if ftype == TType.STRING:
          self.licensenumber = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('RegisterAllInfo')
    if self.username is not None:
      oprot.writeFieldBegin('username', TType.STRING, 1)
      oprot.writeString(self.username)
      oprot.writeFieldEnd()
    if self.password is not None:
      oprot.writeFieldBegin('password', TType.STRING, 2)
      oprot.writeString(self.password)
      oprot.writeFieldEnd()
    if self.bankuser is not None:
      oprot.writeFieldBegin('bankuser', TType.STRING, 3)
      oprot.writeString(self.bankuser)
      oprot.writeFieldEnd()
    if self.idnumber is not None:
      oprot.writeFieldBegin('idnumber', TType.STRING, 4)
      oprot.writeString(self.idnumber)
      oprot.writeFieldEnd()
    if self.banktype is not None:
      oprot.writeFieldBegin('banktype', TType.I32, 5)
      oprot.writeI32(self.banktype)
      oprot.writeFieldEnd()
    if self.bankprovince is not None:
      oprot.writeFieldBegin('bankprovince', TType.STRING, 6)
      oprot.writeString(self.bankprovince)
      oprot.writeFieldEnd()
    if self.bankcity is not None:
      oprot.writeFieldBegin('bankcity', TType.STRING, 7)
      oprot.writeString(self.bankcity)
      oprot.writeFieldEnd()
    if self.bankname is not None:
      oprot.writeFieldBegin('bankname', TType.STRING, 8)
      oprot.writeString(self.bankname)
      oprot.writeFieldEnd()
    if self.headbankname is not None:
      oprot.writeFieldBegin('headbankname', TType.STRING, 9)
      oprot.writeString(self.headbankname)
      oprot.writeFieldEnd()
    if self.bankcode is not None:
      oprot.writeFieldBegin('bankcode', TType.STRING, 10)
      oprot.writeString(self.bankcode)
      oprot.writeFieldEnd()
    if self.bankaccount is not None:
      oprot.writeFieldBegin('bankaccount', TType.STRING, 11)
      oprot.writeString(self.bankaccount)
      oprot.writeFieldEnd()
    if self.bankmobile is not None:
      oprot.writeFieldBegin('bankmobile', TType.STRING, 12)
      oprot.writeString(self.bankmobile)
      oprot.writeFieldEnd()
    if self.shopname is not None:
      oprot.writeFieldBegin('shopname', TType.STRING, 13)
      oprot.writeString(self.shopname)
      oprot.writeFieldEnd()
    if self.province is not None:
      oprot.writeFieldBegin('province', TType.STRING, 14)
      oprot.writeString(self.province)
      oprot.writeFieldEnd()
    if self.city is not None:
      oprot.writeFieldBegin('city', TType.STRING, 15)
      oprot.writeString(self.city)
      oprot.writeFieldEnd()
    if self.address is not None:
      oprot.writeFieldBegin('address', TType.STRING, 16)
      oprot.writeString(self.address)
      oprot.writeFieldEnd()
    if self.landline is not None:
      oprot.writeFieldBegin('landline', TType.STRING, 17)
      oprot.writeString(self.landline)
      oprot.writeFieldEnd()
    if self.longitude is not None:
      oprot.writeFieldBegin('longitude', TType.DOUBLE, 18)
      oprot.writeDouble(self.longitude)
      oprot.writeFieldEnd()
    if self.latitude is not None:
      oprot.writeFieldBegin('latitude', TType.DOUBLE, 19)
      oprot.writeDouble(self.latitude)
      oprot.writeFieldEnd()
    if self.tenpay_ratio is not None:
      oprot.writeFieldBegin('tenpay_ratio', TType.STRING, 20)
      oprot.writeString(self.tenpay_ratio)
      oprot.writeFieldEnd()
    if self.alipay_ratio is not None:
      oprot.writeFieldBegin('alipay_ratio', TType.STRING, 21)
      oprot.writeString(self.alipay_ratio)
      oprot.writeFieldEnd()
    if self.jdpay_ratio is not None:
      oprot.writeFieldBegin('jdpay_ratio', TType.STRING, 22)
      oprot.writeString(self.jdpay_ratio)
      oprot.writeFieldEnd()
    if self.qqpay_ratio is not None:
      oprot.writeFieldBegin('qqpay_ratio', TType.STRING, 23)
      oprot.writeString(self.qqpay_ratio)
      oprot.writeFieldEnd()
    if self.credit_ratio is not None:
      oprot.writeFieldBegin('credit_ratio', TType.STRING, 24)
      oprot.writeString(self.credit_ratio)
      oprot.writeFieldEnd()
    if self.debit_ratio is not None:
      oprot.writeFieldBegin('debit_ratio', TType.STRING, 25)
      oprot.writeString(self.debit_ratio)
      oprot.writeFieldEnd()
    if self.idstatdate is not None:
      oprot.writeFieldBegin('idstatdate', TType.STRING, 26)
      oprot.writeString(self.idstatdate)
      oprot.writeFieldEnd()
    if self.idenddate is not None:
      oprot.writeFieldBegin('idenddate', TType.STRING, 27)
      oprot.writeString(self.idenddate)
      oprot.writeFieldEnd()
    if self.usertype is not None:
      oprot.writeFieldBegin('usertype', TType.I32, 28)
      oprot.writeI32(self.usertype)
      oprot.writeFieldEnd()
    if self.legalperson is not None:
      oprot.writeFieldBegin('legalperson', TType.STRING, 29)
      oprot.writeString(self.legalperson)
      oprot.writeFieldEnd()
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 30)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.mode is not None:
      oprot.writeFieldBegin('mode', TType.STRING, 31)
      oprot.writeString(self.mode)
      oprot.writeFieldEnd()
    if self.big_uid is not None:
      oprot.writeFieldBegin('big_uid', TType.I32, 32)
      oprot.writeI32(self.big_uid)
      oprot.writeFieldEnd()
    if self.imgInfos is not None:
      oprot.writeFieldBegin('imgInfos', TType.LIST, 33)
      oprot.writeListBegin(TType.STRUCT, len(self.imgInfos))
      for iter13 in self.imgInfos:
        iter13.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.mcc is not None:
      oprot.writeFieldBegin('mcc', TType.STRING, 34)
      oprot.writeString(self.mcc)
      oprot.writeFieldEnd()
    if self.groupid is not None:
      oprot.writeFieldBegin('groupid', TType.I32, 35)
      oprot.writeI32(self.groupid)
      oprot.writeFieldEnd()
    if self.userid is not None:
      oprot.writeFieldBegin('userid', TType.I32, 36)
      oprot.writeI32(self.userid)
      oprot.writeFieldEnd()
    if self.src is not None:
      oprot.writeFieldBegin('src', TType.STRING, 37)
      oprot.writeString(self.src)
      oprot.writeFieldEnd()
    if self.licensenumber is not None:
      oprot.writeFieldBegin('licensenumber', TType.STRING, 38)
      oprot.writeString(self.licensenumber)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.username is None:
      raise TProtocol.TProtocolException(message='Required field username is unset!')
    if self.bankuser is None:
      raise TProtocol.TProtocolException(message='Required field bankuser is unset!')
    if self.idnumber is None:
      raise TProtocol.TProtocolException(message='Required field idnumber is unset!')
    if self.bankprovince is None:
      raise TProtocol.TProtocolException(message='Required field bankprovince is unset!')
    if self.bankcity is None:
      raise TProtocol.TProtocolException(message='Required field bankcity is unset!')
    if self.bankname is None:
      raise TProtocol.TProtocolException(message='Required field bankname is unset!')
    if self.headbankname is None:
      raise TProtocol.TProtocolException(message='Required field headbankname is unset!')
    if self.bankcode is None:
      raise TProtocol.TProtocolException(message='Required field bankcode is unset!')
    if self.bankaccount is None:
      raise TProtocol.TProtocolException(message='Required field bankaccount is unset!')
    if self.shopname is None:
      raise TProtocol.TProtocolException(message='Required field shopname is unset!')
    if self.province is None:
      raise TProtocol.TProtocolException(message='Required field province is unset!')
    if self.city is None:
      raise TProtocol.TProtocolException(message='Required field city is unset!')
    if self.address is None:
      raise TProtocol.TProtocolException(message='Required field address is unset!')
    if self.tenpay_ratio is None:
      raise TProtocol.TProtocolException(message='Required field tenpay_ratio is unset!')
    if self.alipay_ratio is None:
      raise TProtocol.TProtocolException(message='Required field alipay_ratio is unset!')
    if self.jdpay_ratio is None:
      raise TProtocol.TProtocolException(message='Required field jdpay_ratio is unset!')
    if self.qqpay_ratio is None:
      raise TProtocol.TProtocolException(message='Required field qqpay_ratio is unset!')
    if self.credit_ratio is None:
      raise TProtocol.TProtocolException(message='Required field credit_ratio is unset!')
    if self.debit_ratio is None:
      raise TProtocol.TProtocolException(message='Required field debit_ratio is unset!')
    if self.imgInfos is None:
      raise TProtocol.TProtocolException(message='Required field imgInfos is unset!')
    if self.mcc is None:
      raise TProtocol.TProtocolException(message='Required field mcc is unset!')
    if self.groupid is None:
      raise TProtocol.TProtocolException(message='Required field groupid is unset!')
    if self.src is None:
      raise TProtocol.TProtocolException(message='Required field src is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.username)
    value = (value * 31) ^ hash(self.password)
    value = (value * 31) ^ hash(self.bankuser)
    value = (value * 31) ^ hash(self.idnumber)
    value = (value * 31) ^ hash(self.banktype)
    value = (value * 31) ^ hash(self.bankprovince)
    value = (value * 31) ^ hash(self.bankcity)
    value = (value * 31) ^ hash(self.bankname)
    value = (value * 31) ^ hash(self.headbankname)
    value = (value * 31) ^ hash(self.bankcode)
    value = (value * 31) ^ hash(self.bankaccount)
    value = (value * 31) ^ hash(self.bankmobile)
    value = (value * 31) ^ hash(self.shopname)
    value = (value * 31) ^ hash(self.province)
    value = (value * 31) ^ hash(self.city)
    value = (value * 31) ^ hash(self.address)
    value = (value * 31) ^ hash(self.landline)
    value = (value * 31) ^ hash(self.longitude)
    value = (value * 31) ^ hash(self.latitude)
    value = (value * 31) ^ hash(self.tenpay_ratio)
    value = (value * 31) ^ hash(self.alipay_ratio)
    value = (value * 31) ^ hash(self.jdpay_ratio)
    value = (value * 31) ^ hash(self.qqpay_ratio)
    value = (value * 31) ^ hash(self.credit_ratio)
    value = (value * 31) ^ hash(self.debit_ratio)
    value = (value * 31) ^ hash(self.idstatdate)
    value = (value * 31) ^ hash(self.idenddate)
    value = (value * 31) ^ hash(self.usertype)
    value = (value * 31) ^ hash(self.legalperson)
    value = (value * 31) ^ hash(self.name)
    value = (value * 31) ^ hash(self.mode)
    value = (value * 31) ^ hash(self.big_uid)
    value = (value * 31) ^ hash(self.imgInfos)
    value = (value * 31) ^ hash(self.mcc)
    value = (value * 31) ^ hash(self.groupid)
    value = (value * 31) ^ hash(self.userid)
    value = (value * 31) ^ hash(self.src)
    value = (value * 31) ^ hash(self.licensenumber)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class UserBrief:
  """
  Attributes:
   - uid
   - shopname
   - email
   - mobile
   - state
   - province
   - city
   - address
   - jointime
   - groupid
   - name
   - username
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'uid', None, 0, ), # 1
    (2, TType.STRING, 'shopname', None, "", ), # 2
    (3, TType.STRING, 'email', None, "", ), # 3
    (4, TType.STRING, 'mobile', None, "", ), # 4
    (5, TType.I32, 'state', None, None, ), # 5
    (6, TType.STRING, 'province', None, None, ), # 6
    (7, TType.STRING, 'city', None, None, ), # 7
    (8, TType.STRING, 'address', None, None, ), # 8
    (9, TType.STRING, 'jointime', None, None, ), # 9
    (10, TType.I32, 'groupid', None, 0, ), # 10
    (11, TType.STRING, 'name', None, "", ), # 11
    (12, TType.STRING, 'username', None, "", ), # 12
  )

  def __init__(self, uid=thrift_spec[1][4], shopname=thrift_spec[2][4], email=thrift_spec[3][4], mobile=thrift_spec[4][4], state=None, province=None, city=None, address=None, jointime=None, groupid=thrift_spec[10][4], name=thrift_spec[11][4], username=thrift_spec[12][4],):
    self.uid = uid
    self.shopname = shopname
    self.email = email
    self.mobile = mobile
    self.state = state
    self.province = province
    self.city = city
    self.address = address
    self.jointime = jointime
    self.groupid = groupid
    self.name = name
    self.username = username

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.uid = iprot.readI64()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.shopname = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.email = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.mobile = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.state = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRING:
          self.province = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.city = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.address = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.STRING:
          self.jointime = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.I32:
          self.groupid = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.STRING:
          self.name = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 12:
        if ftype == TType.STRING:
          self.username = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('UserBrief')
    if self.uid is not None:
      oprot.writeFieldBegin('uid', TType.I64, 1)
      oprot.writeI64(self.uid)
      oprot.writeFieldEnd()
    if self.shopname is not None:
      oprot.writeFieldBegin('shopname', TType.STRING, 2)
      oprot.writeString(self.shopname)
      oprot.writeFieldEnd()
    if self.email is not None:
      oprot.writeFieldBegin('email', TType.STRING, 3)
      oprot.writeString(self.email)
      oprot.writeFieldEnd()
    if self.mobile is not None:
      oprot.writeFieldBegin('mobile', TType.STRING, 4)
      oprot.writeString(self.mobile)
      oprot.writeFieldEnd()
    if self.state is not None:
      oprot.writeFieldBegin('state', TType.I32, 5)
      oprot.writeI32(self.state)
      oprot.writeFieldEnd()
    if self.province is not None:
      oprot.writeFieldBegin('province', TType.STRING, 6)
      oprot.writeString(self.province)
      oprot.writeFieldEnd()
    if self.city is not None:
      oprot.writeFieldBegin('city', TType.STRING, 7)
      oprot.writeString(self.city)
      oprot.writeFieldEnd()
    if self.address is not None:
      oprot.writeFieldBegin('address', TType.STRING, 8)
      oprot.writeString(self.address)
      oprot.writeFieldEnd()
    if self.jointime is not None:
      oprot.writeFieldBegin('jointime', TType.STRING, 9)
      oprot.writeString(self.jointime)
      oprot.writeFieldEnd()
    if self.groupid is not None:
      oprot.writeFieldBegin('groupid', TType.I32, 10)
      oprot.writeI32(self.groupid)
      oprot.writeFieldEnd()
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 11)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.username is not None:
      oprot.writeFieldBegin('username', TType.STRING, 12)
      oprot.writeString(self.username)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.uid is None:
      raise TProtocol.TProtocolException(message='Required field uid is unset!')
    if self.shopname is None:
      raise TProtocol.TProtocolException(message='Required field shopname is unset!')
    if self.email is None:
      raise TProtocol.TProtocolException(message='Required field email is unset!')
    if self.mobile is None:
      raise TProtocol.TProtocolException(message='Required field mobile is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.uid)
    value = (value * 31) ^ hash(self.shopname)
    value = (value * 31) ^ hash(self.email)
    value = (value * 31) ^ hash(self.mobile)
    value = (value * 31) ^ hash(self.state)
    value = (value * 31) ^ hash(self.province)
    value = (value * 31) ^ hash(self.city)
    value = (value * 31) ^ hash(self.address)
    value = (value * 31) ^ hash(self.jointime)
    value = (value * 31) ^ hash(self.groupid)
    value = (value * 31) ^ hash(self.name)
    value = (value * 31) ^ hash(self.username)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class UserExt:
  """
  Attributes:
   - uid
   - regionid
   - shoptype_id
   - contact
   - logo_url
   - head_img
   - ctime
   - utime
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'uid', None, 0, ), # 1
    (2, TType.I64, 'regionid', None, None, ), # 2
    (3, TType.I64, 'shoptype_id', None, None, ), # 3
    (4, TType.STRING, 'contact', None, None, ), # 4
    (5, TType.STRING, 'logo_url', None, None, ), # 5
    (6, TType.STRING, 'head_img', None, None, ), # 6
    (7, TType.STRING, 'ctime', None, None, ), # 7
    (8, TType.STRING, 'utime', None, None, ), # 8
  )

  def __init__(self, uid=thrift_spec[1][4], regionid=None, shoptype_id=None, contact=None, logo_url=None, head_img=None, ctime=None, utime=None,):
    self.uid = uid
    self.regionid = regionid
    self.shoptype_id = shoptype_id
    self.contact = contact
    self.logo_url = logo_url
    self.head_img = head_img
    self.ctime = ctime
    self.utime = utime

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.uid = iprot.readI64()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I64:
          self.regionid = iprot.readI64()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I64:
          self.shoptype_id = iprot.readI64()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.contact = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.logo_url = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRING:
          self.head_img = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.ctime = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.utime = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('UserExt')
    if self.uid is not None:
      oprot.writeFieldBegin('uid', TType.I64, 1)
      oprot.writeI64(self.uid)
      oprot.writeFieldEnd()
    if self.regionid is not None:
      oprot.writeFieldBegin('regionid', TType.I64, 2)
      oprot.writeI64(self.regionid)
      oprot.writeFieldEnd()
    if self.shoptype_id is not None:
      oprot.writeFieldBegin('shoptype_id', TType.I64, 3)
      oprot.writeI64(self.shoptype_id)
      oprot.writeFieldEnd()
    if self.contact is not None:
      oprot.writeFieldBegin('contact', TType.STRING, 4)
      oprot.writeString(self.contact)
      oprot.writeFieldEnd()
    if self.logo_url is not None:
      oprot.writeFieldBegin('logo_url', TType.STRING, 5)
      oprot.writeString(self.logo_url)
      oprot.writeFieldEnd()
    if self.head_img is not None:
      oprot.writeFieldBegin('head_img', TType.STRING, 6)
      oprot.writeString(self.head_img)
      oprot.writeFieldEnd()
    if self.ctime is not None:
      oprot.writeFieldBegin('ctime', TType.STRING, 7)
      oprot.writeString(self.ctime)
      oprot.writeFieldEnd()
    if self.utime is not None:
      oprot.writeFieldBegin('utime', TType.STRING, 8)
      oprot.writeString(self.utime)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.uid is None:
      raise TProtocol.TProtocolException(message='Required field uid is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.uid)
    value = (value * 31) ^ hash(self.regionid)
    value = (value * 31) ^ hash(self.shoptype_id)
    value = (value * 31) ^ hash(self.contact)
    value = (value * 31) ^ hash(self.logo_url)
    value = (value * 31) ^ hash(self.head_img)
    value = (value * 31) ^ hash(self.ctime)
    value = (value * 31) ^ hash(self.utime)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Opuser:
  """
  Attributes:
   - uid
   - opuid
   - opname
   - mobile
   - password
   - status
   - ctime
   - utime
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'uid', None, 0, ), # 1
    (2, TType.I64, 'opuid', None, 0, ), # 2
    (3, TType.STRING, 'opname', None, None, ), # 3
    (4, TType.STRING, 'mobile', None, None, ), # 4
    (5, TType.STRING, 'password', None, None, ), # 5
    (6, TType.I32, 'status', None, None, ), # 6
    (7, TType.STRING, 'ctime', None, None, ), # 7
    (8, TType.STRING, 'utime', None, None, ), # 8
  )

  def __init__(self, uid=thrift_spec[1][4], opuid=thrift_spec[2][4], opname=None, mobile=None, password=None, status=None, ctime=None, utime=None,):
    self.uid = uid
    self.opuid = opuid
    self.opname = opname
    self.mobile = mobile
    self.password = password
    self.status = status
    self.ctime = ctime
    self.utime = utime

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.uid = iprot.readI64()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I64:
          self.opuid = iprot.readI64()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.opname = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.mobile = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.password = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.status = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.ctime = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.utime = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Opuser')
    if self.uid is not None:
      oprot.writeFieldBegin('uid', TType.I64, 1)
      oprot.writeI64(self.uid)
      oprot.writeFieldEnd()
    if self.opuid is not None:
      oprot.writeFieldBegin('opuid', TType.I64, 2)
      oprot.writeI64(self.opuid)
      oprot.writeFieldEnd()
    if self.opname is not None:
      oprot.writeFieldBegin('opname', TType.STRING, 3)
      oprot.writeString(self.opname)
      oprot.writeFieldEnd()
    if self.mobile is not None:
      oprot.writeFieldBegin('mobile', TType.STRING, 4)
      oprot.writeString(self.mobile)
      oprot.writeFieldEnd()
    if self.password is not None:
      oprot.writeFieldBegin('password', TType.STRING, 5)
      oprot.writeString(self.password)
      oprot.writeFieldEnd()
    if self.status is not None:
      oprot.writeFieldBegin('status', TType.I32, 6)
      oprot.writeI32(self.status)
      oprot.writeFieldEnd()
    if self.ctime is not None:
      oprot.writeFieldBegin('ctime', TType.STRING, 7)
      oprot.writeString(self.ctime)
      oprot.writeFieldEnd()
    if self.utime is not None:
      oprot.writeFieldBegin('utime', TType.STRING, 8)
      oprot.writeString(self.utime)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.uid is None:
      raise TProtocol.TProtocolException(message='Required field uid is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.uid)
    value = (value * 31) ^ hash(self.opuid)
    value = (value * 31) ^ hash(self.opname)
    value = (value * 31) ^ hash(self.mobile)
    value = (value * 31) ^ hash(self.password)
    value = (value * 31) ^ hash(self.status)
    value = (value * 31) ^ hash(self.ctime)
    value = (value * 31) ^ hash(self.utime)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class UserProfile:
  """
  Attributes:
   - uid
   - user
   - bankInfo
   - userTags
   - relations
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'uid', None, 0, ), # 1
    (2, TType.STRUCT, 'user', (User, User.thrift_spec), None, ), # 2
    (3, TType.STRUCT, 'bankInfo', (BankInfo, BankInfo.thrift_spec), None, ), # 3
    (4, TType.LIST, 'userTags', (TType.STRUCT,(UserTag, UserTag.thrift_spec)), None, ), # 4
    (5, TType.LIST, 'relations', (TType.STRUCT,(User, User.thrift_spec)), None, ), # 5
  )

  def __init__(self, uid=thrift_spec[1][4], user=None, bankInfo=None, userTags=None, relations=None,):
    self.uid = uid
    self.user = user
    self.bankInfo = bankInfo
    self.userTags = userTags
    self.relations = relations

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.uid = iprot.readI64()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.user = User()
          self.user.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.bankInfo = BankInfo()
          self.bankInfo.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.LIST:
          self.userTags = []
          (_etype17, _size14) = iprot.readListBegin()
          for _i18 in xrange(_size14):
            _elem19 = UserTag()
            _elem19.read(iprot)
            self.userTags.append(_elem19)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.LIST:
          self.relations = []
          (_etype23, _size20) = iprot.readListBegin()
          for _i24 in xrange(_size20):
            _elem25 = User()
            _elem25.read(iprot)
            self.relations.append(_elem25)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('UserProfile')
    if self.uid is not None:
      oprot.writeFieldBegin('uid', TType.I64, 1)
      oprot.writeI64(self.uid)
      oprot.writeFieldEnd()
    if self.user is not None:
      oprot.writeFieldBegin('user', TType.STRUCT, 2)
      self.user.write(oprot)
      oprot.writeFieldEnd()
    if self.bankInfo is not None:
      oprot.writeFieldBegin('bankInfo', TType.STRUCT, 3)
      self.bankInfo.write(oprot)
      oprot.writeFieldEnd()
    if self.userTags is not None:
      oprot.writeFieldBegin('userTags', TType.LIST, 4)
      oprot.writeListBegin(TType.STRUCT, len(self.userTags))
      for iter26 in self.userTags:
        iter26.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.relations is not None:
      oprot.writeFieldBegin('relations', TType.LIST, 5)
      oprot.writeListBegin(TType.STRUCT, len(self.relations))
      for iter27 in self.relations:
        iter27.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.uid is None:
      raise TProtocol.TProtocolException(message='Required field uid is unset!')
    if self.user is None:
      raise TProtocol.TProtocolException(message='Required field user is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.uid)
    value = (value * 31) ^ hash(self.user)
    value = (value * 31) ^ hash(self.bankInfo)
    value = (value * 31) ^ hash(self.userTags)
    value = (value * 31) ^ hash(self.relations)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class UserQuery:
  """
  Attributes:
   - uids
   - mobiles
   - state
   - names
   - catenames
   - tagnames
  """

  thrift_spec = (
    None, # 0
    (1, TType.LIST, 'uids', (TType.I64,None), None, ), # 1
    (2, TType.LIST, 'mobiles', (TType.STRING,None), None, ), # 2
    (3, TType.I32, 'state', None, None, ), # 3
    (4, TType.LIST, 'names', (TType.STRING,None), None, ), # 4
    (5, TType.LIST, 'catenames', (TType.STRING,None), None, ), # 5
    (6, TType.LIST, 'tagnames', (TType.STRING,None), None, ), # 6
  )

  def __init__(self, uids=None, mobiles=None, state=None, names=None, catenames=None, tagnames=None,):
    self.uids = uids
    self.mobiles = mobiles
    self.state = state
    self.names = names
    self.catenames = catenames
    self.tagnames = tagnames

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.LIST:
          self.uids = []
          (_etype31, _size28) = iprot.readListBegin()
          for _i32 in xrange(_size28):
            _elem33 = iprot.readI64()
            self.uids.append(_elem33)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.mobiles = []
          (_etype37, _size34) = iprot.readListBegin()
          for _i38 in xrange(_size34):
            _elem39 = iprot.readString()
            self.mobiles.append(_elem39)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.state = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.LIST:
          self.names = []
          (_etype43, _size40) = iprot.readListBegin()
          for _i44 in xrange(_size40):
            _elem45 = iprot.readString()
            self.names.append(_elem45)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.LIST:
          self.catenames = []
          (_etype49, _size46) = iprot.readListBegin()
          for _i50 in xrange(_size46):
            _elem51 = iprot.readString()
            self.catenames.append(_elem51)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.LIST:
          self.tagnames = []
          (_etype55, _size52) = iprot.readListBegin()
          for _i56 in xrange(_size52):
            _elem57 = iprot.readString()
            self.tagnames.append(_elem57)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('UserQuery')
    if self.uids is not None:
      oprot.writeFieldBegin('uids', TType.LIST, 1)
      oprot.writeListBegin(TType.I64, len(self.uids))
      for iter58 in self.uids:
        oprot.writeI64(iter58)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.mobiles is not None:
      oprot.writeFieldBegin('mobiles', TType.LIST, 2)
      oprot.writeListBegin(TType.STRING, len(self.mobiles))
      for iter59 in self.mobiles:
        oprot.writeString(iter59)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.state is not None:
      oprot.writeFieldBegin('state', TType.I32, 3)
      oprot.writeI32(self.state)
      oprot.writeFieldEnd()
    if self.names is not None:
      oprot.writeFieldBegin('names', TType.LIST, 4)
      oprot.writeListBegin(TType.STRING, len(self.names))
      for iter60 in self.names:
        oprot.writeString(iter60)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.catenames is not None:
      oprot.writeFieldBegin('catenames', TType.LIST, 5)
      oprot.writeListBegin(TType.STRING, len(self.catenames))
      for iter61 in self.catenames:
        oprot.writeString(iter61)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.tagnames is not None:
      oprot.writeFieldBegin('tagnames', TType.LIST, 6)
      oprot.writeListBegin(TType.STRING, len(self.tagnames))
      for iter62 in self.tagnames:
        oprot.writeString(iter62)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.uids)
    value = (value * 31) ^ hash(self.mobiles)
    value = (value * 31) ^ hash(self.state)
    value = (value * 31) ^ hash(self.names)
    value = (value * 31) ^ hash(self.catenames)
    value = (value * 31) ^ hash(self.tagnames)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class UserRelation:
  """
  Attributes:
   - userid
   - link_cate
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'userid', None, None, ), # 1
    (2, TType.STRING, 'link_cate', None, None, ), # 2
  )

  def __init__(self, userid=None, link_cate=None,):
    self.userid = userid
    self.link_cate = link_cate

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.userid = iprot.readI64()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.link_cate = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('UserRelation')
    if self.userid is not None:
      oprot.writeFieldBegin('userid', TType.I64, 1)
      oprot.writeI64(self.userid)
      oprot.writeFieldEnd()
    if self.link_cate is not None:
      oprot.writeFieldBegin('link_cate', TType.STRING, 2)
      oprot.writeString(self.link_cate)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.userid)
    value = (value * 31) ^ hash(self.link_cate)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Permission:
  """
  Attributes:
   - name
   - code
   - group
   - id
   - status
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'name', None, None, ), # 1
    (2, TType.STRING, 'code', None, None, ), # 2
    (3, TType.STRING, 'group', None, None, ), # 3
    (4, TType.I64, 'id', None, None, ), # 4
    (5, TType.I32, 'status', None, None, ), # 5
  )

  def __init__(self, name=None, code=None, group=None, id=None, status=None,):
    self.name = name
    self.code = code
    self.group = group
    self.id = id
    self.status = status

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.name = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.code = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.group = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I64:
          self.id = iprot.readI64()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.status = iprot.readI32()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Permission')
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 1)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.code is not None:
      oprot.writeFieldBegin('code', TType.STRING, 2)
      oprot.writeString(self.code)
      oprot.writeFieldEnd()
    if self.group is not None:
      oprot.writeFieldBegin('group', TType.STRING, 3)
      oprot.writeString(self.group)
      oprot.writeFieldEnd()
    if self.id is not None:
      oprot.writeFieldBegin('id', TType.I64, 4)
      oprot.writeI64(self.id)
      oprot.writeFieldEnd()
    if self.status is not None:
      oprot.writeFieldBegin('status', TType.I32, 5)
      oprot.writeI32(self.status)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.name)
    value = (value * 31) ^ hash(self.code)
    value = (value * 31) ^ hash(self.group)
    value = (value * 31) ^ hash(self.id)
    value = (value * 31) ^ hash(self.status)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class PermissionRole:
  """
  Attributes:
   - name
   - code
   - group
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'name', None, None, ), # 1
    (2, TType.STRING, 'code', None, None, ), # 2
    (3, TType.STRING, 'group', None, None, ), # 3
  )

  def __init__(self, name=None, code=None, group=None,):
    self.name = name
    self.code = code
    self.group = group

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.name = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.code = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.group = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('PermissionRole')
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 1)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.code is not None:
      oprot.writeFieldBegin('code', TType.STRING, 2)
      oprot.writeString(self.code)
      oprot.writeFieldEnd()
    if self.group is not None:
      oprot.writeFieldBegin('group', TType.STRING, 3)
      oprot.writeString(self.group)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.name)
    value = (value * 31) ^ hash(self.code)
    value = (value * 31) ^ hash(self.group)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class ApolloException(TException):
  """
  Attributes:
   - respcd
   - respmsg
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'respcd', None, None, ), # 1
    (2, TType.STRING, 'respmsg', None, None, ), # 2
  )

  def __init__(self, respcd=None, respmsg=None,):
    self.respcd = respcd
    self.respmsg = respmsg

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.respcd = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.respmsg = iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('ApolloException')
    if self.respcd is not None:
      oprot.writeFieldBegin('respcd', TType.STRING, 1)
      oprot.writeString(self.respcd)
      oprot.writeFieldEnd()
    if self.respmsg is not None:
      oprot.writeFieldBegin('respmsg', TType.STRING, 2)
      oprot.writeString(self.respmsg)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __str__(self):
    return repr(self)

  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.respcd)
    value = (value * 31) ^ hash(self.respmsg)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
