#
# Autogenerated by Thrift Compiler (0.7.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class TradeStatus:
  PROCESSING = 0
  SUCCESS = 1
  FAILED = 2
  REFUNDED = 3

  _VALUES_TO_NAMES = {
    0: "PROCESSING",
    1: "SUCCESS",
    2: "FAILED",
    3: "REFUNDED",
  }

  _NAMES_TO_VALUES = {
    "PROCESSING": 0,
    "SUCCESS": 1,
    "FAILED": 2,
    "REFUNDED": 3,
  }

class BatchStatus:
  PROCESSING = 0
  SUCCESS = 1
  FAILED = 2

  _VALUES_TO_NAMES = {
    0: "PROCESSING",
    1: "SUCCESS",
    2: "FAILED",
  }

  _NAMES_TO_VALUES = {
    "PROCESSING": 0,
    "SUCCESS": 1,
    "FAILED": 2,
  }

class AccountType:
  DEBIT = 0
  CREDIT = 1
  CORPORATE = 2

  _VALUES_TO_NAMES = {
    0: "DEBIT",
    1: "CREDIT",
    2: "CORPORATE",
  }

  _NAMES_TO_VALUES = {
    "DEBIT": 0,
    "CREDIT": 1,
    "CORPORATE": 2,
  }

class TradeType:
  Batch = 2

  _VALUES_TO_NAMES = {
    2: "Batch",
  }

  _NAMES_TO_VALUES = {
    "Batch": 2,
  }

